"""
Audio Ducker - Lowers music/ambience during dialogue.

This is a POST-PRODUCTION module. It assumes audio tracks already exist
(generated by sonic/mixer.py) and applies dynamic volume adjustments.

What This Does:
    "Ducking" is a standard film technique where background music
    automatically lowers when dialogue plays, then rises back up.
    
    BEFORE: Music at 100%, dialogue at 100% → dialogue gets buried
    AFTER:  Music ducks to 30% during dialogue → dialogue is clear

What This Does NOT Do:
    - Generate audio (that's sonic/tts_engine.py, ambience.py, etc.)
    - Combine/mix tracks (that's sonic/mixer.py)
    - Final video assembly (that's stitcher.py)

Technical Approach:
    Uses FFmpeg's sidechaincompress filter, which uses one audio signal
    (dialogue) to control the volume of another (music).

Usage:
    from src.post.audio_ducker import AudioDucker
    
    ducker = AudioDucker()
    
    # Duck music under dialogue
    result = await ducker.duck(
        music_path=Path("music.wav"),
        dialogue_path=Path("dialogue.wav"),
        output_path=Path("ducked_music.wav"),
    )
    
    # Or apply to a video with embedded audio tracks
    result = await ducker.duck_video(
        video_path=Path("video_with_audio.mp4"),
        dialogue_path=Path("dialogue.wav"),
        output_path=Path("video_ducked.mp4"),
    )
"""

import asyncio
import logging
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional, Dict, Any, List

from .ffmpeg_wrapper import (
    run_ffmpeg,
    probe_video,
    VideoInfo,
    FFmpegExecutionError,
)

logger = logging.getLogger(__name__)


# =============================================================================
# CONSTANTS
# =============================================================================

# Default ducking parameters (industry-standard starting points)
DEFAULT_DUCK_LEVEL_DB = -12.0      # How much to reduce music (in dB)
DEFAULT_THRESHOLD_DB = -30.0       # Dialogue level that triggers ducking
DEFAULT_ATTACK_MS = 50.0           # How fast ducking kicks in
DEFAULT_RELEASE_MS = 300.0         # How fast volume recovers
DEFAULT_RATIO = 8.0                # Compression ratio when ducking


# =============================================================================
# DATA STRUCTURES
# =============================================================================

@dataclass
class DuckingParams:
    """
    Parameters controlling the ducking behavior.
    
    Attributes:
        duck_level_db: How much to reduce the music volume (negative dB)
        threshold_db: Dialogue level that triggers ducking (negative dB)
        attack_ms: How quickly ducking engages (milliseconds)
        release_ms: How quickly volume recovers after dialogue (milliseconds)
        ratio: Compression ratio (higher = more aggressive ducking)
    """
    duck_level_db: float = DEFAULT_DUCK_LEVEL_DB
    threshold_db: float = DEFAULT_THRESHOLD_DB
    attack_ms: float = DEFAULT_ATTACK_MS
    release_ms: float = DEFAULT_RELEASE_MS
    ratio: float = DEFAULT_RATIO
    
    def validate(self) -> List[str]:
        """Validate parameters are in sensible ranges."""
        errors = []
        
        if self.duck_level_db > 0:
            errors.append("duck_level_db should be negative (it's a reduction)")
        
        if self.duck_level_db < -60:
            errors.append("duck_level_db below -60dB is essentially silence")
        
        if self.attack_ms < 1:
            errors.append("attack_ms too short, may cause clicking")
        
        if self.release_ms < 10:
            errors.append("release_ms too short, will sound unnatural")
        
        if self.ratio < 1:
            errors.append("ratio must be >= 1")
        
        return errors
    
    @classmethod
    def gentle(cls) -> "DuckingParams":
        """Preset for subtle ducking (podcast style)."""
        return cls(
            duck_level_db=-6.0,
            threshold_db=-35.0,
            attack_ms=100.0,
            release_ms=500.0,
            ratio=4.0,
        )
    
    @classmethod
    def standard(cls) -> "DuckingParams":
        """Preset for typical film/video ducking."""
        return cls(
            duck_level_db=-12.0,
            threshold_db=-30.0,
            attack_ms=50.0,
            release_ms=300.0,
            ratio=8.0,
        )
    
    @classmethod
    def aggressive(cls) -> "DuckingParams":
        """Preset for heavy ducking (dialogue must be crystal clear)."""
        return cls(
            duck_level_db=-20.0,
            threshold_db=-25.0,
            attack_ms=20.0,
            release_ms=200.0,
            ratio=12.0,
        )


@dataclass
class DuckResult:
    """
    Result of a ducking operation.
    
    Attributes:
        success: Whether the operation completed
        output_path: Path to the ducked audio/video
        params_used: The ducking parameters that were applied
        processing_time_sec: How long the operation took
        warnings: Non-fatal issues encountered
        error: Error message if failed
    """
    success: bool
    output_path: Optional[Path] = None
    params_used: Optional[DuckingParams] = None
    processing_time_sec: float = 0.0
    warnings: List[str] = field(default_factory=list)
    error: Optional[str] = None
    
    @classmethod
    def failed(cls, error: str) -> "DuckResult":
        """Factory for failed result."""
        return cls(success=False, error=error)


# =============================================================================
# AUDIO DUCKER CLASS
# =============================================================================

class AudioDucker:
    """
    Applies ducking to lower music/ambience during dialogue.
    
    This is the audio equivalent of "the music gets quieter when
    someone talks, then comes back up after."
    
    Attributes:
        default_params: Default ducking parameters to use
    """
    
    def __init__(self, default_params: Optional[DuckingParams] = None):
        """
        Initialize the audio ducker.
        
        Args:
            default_params: Default parameters (None = standard preset)
        """
        self.default_params = default_params or DuckingParams.standard()
    
    # =========================================================================
    # PUBLIC API
    # =========================================================================
    
    async def duck(
        self,
        music_path: Path,
        dialogue_path: Path,
        output_path: Path,
        params: Optional[DuckingParams] = None,
    ) -> DuckResult:
        """
        Apply ducking to an audio track using dialogue as the trigger.
        
        The dialogue track controls WHEN ducking happens.
        The music track is WHAT gets ducked.
        
        Args:
            music_path: Audio to duck (music, ambience, etc.)
            dialogue_path: Audio that triggers ducking (speech)
            output_path: Where to write the ducked audio
            params: Ducking parameters (None = use defaults)
            
        Returns:
            DuckResult with success status
        """
        start_time = time.monotonic()
        params = params or self.default_params
        
        # Validate params
        errors = params.validate()
        if errors:
            return DuckResult.failed(f"Invalid parameters: {'; '.join(errors)}")
        
        # Validate inputs exist
        music_path = Path(music_path)
        dialogue_path = Path(dialogue_path)
        output_path = Path(output_path)
        
        if not music_path.exists():
            return DuckResult.failed(f"Music file not found: {music_path}")
        
        if not dialogue_path.exists():
            return DuckResult.failed(f"Dialogue file not found: {dialogue_path}")
        
        logger.info(f"Ducking {music_path.name} under {dialogue_path.name}")
        
        try:
            await self._apply_sidechain_duck(
                music_path, 
                dialogue_path, 
                output_path, 
                params
            )
            
            processing_time = time.monotonic() - start_time
            
            return DuckResult(
                success=True,
                output_path=output_path,
                params_used=params,
                processing_time_sec=processing_time,
            )
            
        except FFmpegExecutionError as e:
            logger.error(f"FFmpeg ducking failed: {e}")
            return DuckResult.failed(f"FFmpeg error: {e}")
        except Exception as e:
            logger.exception(f"Ducking failed: {e}")
            return DuckResult.failed(str(e))
    
    async def duck_video(
        self,
        video_path: Path,
        dialogue_path: Path,
        output_path: Path,
        params: Optional[DuckingParams] = None,
    ) -> DuckResult:
        """
        Apply ducking to a video's audio track.
        
        Extracts the video's audio, applies ducking using the dialogue
        as trigger, then muxes the ducked audio back with the video.
        
        Args:
            video_path: Video with audio to duck
            dialogue_path: Dialogue track that triggers ducking
            output_path: Where to write the output video
            params: Ducking parameters
            
        Returns:
            DuckResult with success status
        """
        start_time = time.monotonic()
        params = params or self.default_params
        
        video_path = Path(video_path)
        dialogue_path = Path(dialogue_path)
        output_path = Path(output_path)
        
        if not video_path.exists():
            return DuckResult.failed(f"Video file not found: {video_path}")
        
        if not dialogue_path.exists():
            return DuckResult.failed(f"Dialogue file not found: {dialogue_path}")
        
        # Check video has audio
        info = await probe_video(video_path)
        if not info.has_audio:
            return DuckResult.failed(f"Video has no audio track: {video_path}")
        
        logger.info(f"Ducking audio in {video_path.name}")
        
        try:
            await self._apply_sidechain_duck_video(
                video_path,
                dialogue_path,
                output_path,
                params,
            )
            
            processing_time = time.monotonic() - start_time
            
            return DuckResult(
                success=True,
                output_path=output_path,
                params_used=params,
                processing_time_sec=processing_time,
            )
            
        except FFmpegExecutionError as e:
            logger.error(f"FFmpeg video ducking failed: {e}")
            return DuckResult.failed(f"FFmpeg error: {e}")
        except Exception as e:
            logger.exception(f"Video ducking failed: {e}")
            return DuckResult.failed(str(e))
    
    async def duck_under_itself(
        self,
        audio_path: Path,
        output_path: Path,
        params: Optional[DuckingParams] = None,
    ) -> DuckResult:
        """
        Apply auto-ducking based on speech detection in the same track.
        
        Useful when dialogue and music are already mixed and you want
        to reduce music during speech parts. Uses FFmpeg's speech
        detection to find dialogue segments.
        
        Note: Less precise than using a separate dialogue track.
        
        Args:
            audio_path: Audio with both music and dialogue
            output_path: Where to write ducked audio
            params: Ducking parameters
            
        Returns:
            DuckResult with success status
        """
        start_time = time.monotonic()
        params = params or self.default_params
        
        audio_path = Path(audio_path)
        output_path = Path(output_path)
        
        if not audio_path.exists():
            return DuckResult.failed(f"Audio file not found: {audio_path}")
        
        logger.info(f"Auto-ducking {audio_path.name} based on speech detection")
        
        try:
            # Use compand filter with speech-frequency emphasis
            # This is a simpler approach than full sidechain
            await self._apply_speech_aware_compression(
                audio_path,
                output_path,
                params,
            )
            
            processing_time = time.monotonic() - start_time
            
            return DuckResult(
                success=True,
                output_path=output_path,
                params_used=params,
                processing_time_sec=processing_time,
                warnings=["Auto-ducking is less precise than separate tracks"],
            )
            
        except FFmpegExecutionError as e:
            return DuckResult.failed(f"FFmpeg error: {e}")
        except Exception as e:
            return DuckResult.failed(str(e))
    
    # =========================================================================
    # INTERNAL: FFmpeg Implementations
    # =========================================================================
    
    async def _apply_sidechain_duck(
        self,
        music_path: Path,
        dialogue_path: Path,
        output_path: Path,
        params: DuckingParams,
    ) -> None:
        """
        Apply sidechain compression using FFmpeg.
        
        The sidechaincompress filter uses the dialogue track's volume
        to control how much the music track is compressed.
        """
        # Build the filter complex
        # Input 0: music (what gets ducked)
        # Input 1: dialogue (what triggers ducking)
        
        # Convert params to FFmpeg filter syntax
        # sidechaincompress: threshold, ratio, attack, release
        filter_complex = (
            f"[0:a][1:a]sidechaincompress="
            f"threshold={self._db_to_ratio(params.threshold_db)}:"
            f"ratio={params.ratio}:"
            f"attack={params.attack_ms}:"
            f"release={params.release_ms}:"
            f"level_sc=1"  # Use full sidechain signal
            f"[ducked]"
        )
        
        args = [
            "-i", str(music_path),
            "-i", str(dialogue_path),
            "-filter_complex", filter_complex,
            "-map", "[ducked]",
            "-c:a", "aac",
            "-b:a", "192k",
            str(output_path),
        ]
        
        await run_ffmpeg(args, output_path=output_path)
    
    async def _apply_sidechain_duck_video(
        self,
        video_path: Path,
        dialogue_path: Path,
        output_path: Path,
        params: DuckingParams,
    ) -> None:
        """
        Apply sidechain ducking to video's audio, keeping video intact.
        """
        # Filter complex with video passthrough
        filter_complex = (
            f"[0:a][1:a]sidechaincompress="
            f"threshold={self._db_to_ratio(params.threshold_db)}:"
            f"ratio={params.ratio}:"
            f"attack={params.attack_ms}:"
            f"release={params.release_ms}:"
            f"level_sc=1"
            f"[ducked]"
        )
        
        args = [
            "-i", str(video_path),
            "-i", str(dialogue_path),
            "-filter_complex", filter_complex,
            "-map", "0:v",        # Keep video from input 0
            "-map", "[ducked]",   # Use ducked audio
            "-c:v", "copy",       # Don't re-encode video
            "-c:a", "aac",
            "-b:a", "192k",
            str(output_path),
        ]
        
        await run_ffmpeg(args, output_path=output_path)
    
    async def _apply_speech_aware_compression(
        self,
        audio_path: Path,
        output_path: Path,
        params: DuckingParams,
    ) -> None:
        """
        Apply compression that responds to speech frequencies.
        
        This is a simpler approach when we don't have separate tracks.
        Uses highpass + compressor to target speech frequencies (300-3000Hz).
        """
        # Create a speech-detection sidechain using frequency filtering
        # 1. Extract speech frequencies (300-3000Hz) as sidechain
        # 2. Use that to duck the full mix
        
        filter_complex = (
            # Split input
            f"[0:a]asplit=2[main][sc];"
            # Create sidechain from speech frequencies
            f"[sc]highpass=f=300,lowpass=f=3000[speech];"
            # Apply sidechain compression
            f"[main][speech]sidechaincompress="
            f"threshold={self._db_to_ratio(params.threshold_db)}:"
            f"ratio={params.ratio}:"
            f"attack={params.attack_ms}:"
            f"release={params.release_ms}"
            f"[ducked]"
        )
        
        args = [
            "-i", str(audio_path),
            "-filter_complex", filter_complex,
            "-map", "[ducked]",
            "-c:a", "aac",
            "-b:a", "192k",
            str(output_path),
        ]
        
        await run_ffmpeg(args, output_path=output_path)
    
    def _db_to_ratio(self, db: float) -> float:
        """
        Convert decibels to linear ratio for FFmpeg.
        
        FFmpeg's threshold expects a ratio (0-1), not dB.
        -30dB ≈ 0.0316
        """
        return 10 ** (db / 20)


# =============================================================================
# CONVENIENCE FUNCTIONS
# =============================================================================

async def duck_music(
    music_path: Path,
    dialogue_path: Path,
    output_path: Path,
    preset: str = "standard",
) -> DuckResult:
    """
    Convenience function to duck music under dialogue.
    
    Args:
        music_path: Music/ambience to duck
        dialogue_path: Dialogue that triggers ducking
        output_path: Where to write output
        preset: "gentle", "standard", or "aggressive"
        
    Returns:
        DuckResult
    """
    presets = {
        "gentle": DuckingParams.gentle(),
        "standard": DuckingParams.standard(),
        "aggressive": DuckingParams.aggressive(),
    }
    
    params = presets.get(preset, DuckingParams.standard())
    ducker = AudioDucker(default_params=params)
    
    return await ducker.duck(music_path, dialogue_path, output_path)


async def duck_video_audio(
    video_path: Path,
    dialogue_path: Path,
    output_path: Path,
    duck_level_db: float = DEFAULT_DUCK_LEVEL_DB,
) -> DuckResult:
    """
    Convenience function to duck a video's audio under dialogue.
    
    Args:
        video_path: Video with music/ambience
        dialogue_path: Dialogue track
        output_path: Where to write output video
        duck_level_db: How much to reduce (default -12dB)
        
    Returns:
        DuckResult
    """
    params = DuckingParams(duck_level_db=duck_level_db)
    ducker = AudioDucker(default_params=params)
    
    return await ducker.duck_video(video_path, dialogue_path, output_path)


# =============================================================================
# EXPORTS
# =============================================================================

__all__ = [
    # Data structures
    "DuckingParams",
    "DuckResult",
    
    # Main class
    "AudioDucker",
    
    # Convenience functions
    "duck_music",
    "duck_video_audio",
]